=== 4850-XML/4850Lab7/data/classSchedule.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Document   : classSchedule.dtd
    Created on : March 03, 2016, 11:18 PM
    Author     : Khang Tran
    Description:
        This is the core structure of our winter 2016 
        timetable. A semester can have as many days elements, each days element 
        contains a timeslot and each timeslot can have one course. 
-->


<!-- The root element contains a week element, and then multiple source elements,
each of which models data from a specific course.
 -->
<!ELEMENT schedule (days,timeslots,courses)>

<!-- The days element contains a daySchedule child element (1 or more) -->
<!ELEMENT days (daySchedule+)>
<!-- The daySchedule element contains a daySchedule child element (1 or more) -->
<!ELEMENT daySchedule (timeslot*|course)>
<!ATTLIST daySchedule
    day (Monday|Tuesday|Wednesday|Thursday|Friday) #REQUIRED
>

<!-- The timeslots element contains all the course timeslots of the week -->
<!ELEMENT timeslots (timeslot+)>
<!ELEMENT timeslot (daySchedule|course)>
<!ATTLIST timeslot
    start CDATA #REQUIRED
    finish CDATA #REQUIRED 
>

<!-- The courses element contains all the courses that we are enrolled in -->
<!ELEMENT courses (course+)>
<!-- The course element contains a courseID, className, and classLocation
elements
-->
<!ELEMENT course (courseID, className, classLocation, classActivity)>

<!ELEMENT courseID (#PCDATA)>
<!ELEMENT className (#PCDATA)>
<!ELEMENT classLocation (#PCDATA)>
<!ELEMENT classActivity (#PCDATA)>

<!ATTLIST courseID
    id (4850|4770|4620) #REQUIRED
>
<!ATTLIST classActivity
    activity (lab|lecture|tutorial) #IMPLIED
>

=== 4850-XML/4850Lab7/data/timeslot_facet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE timeslots SYSTEM "classSchedule.dtd">

<timeslots>
    <timeslot start="13:30" finish="15:30">
        <daySchedule day ="Monday">
            <course>
                <courseID id="4770"></courseID>
                <className></className>
                <classLocation></classLocation>
                <classActivity activity="tutorial"></classActivity>
            </course>
        </daySchedule>
    </timeslot>
    <timeslot start="10:30" finish="12:30">
        <daySchedule day ="Tuesday">
            <course>
                <courseID id="4620"></courseID>
                <className></className> 
                <classLocation></classLocation>
                <classActivity activity="lab"></classActivity>
            </course>
        </daySchedule>
    </timeslot>
    <timeslot start="15:30" finish="17:30">
        <daySchedule day ="Tuesday">
            <course>
                <courseID id="4620"></courseID>
                <className></className> 
                <classLocation></classLocation>
                <classActivity activity="lecture"></classActivity>
            </course>
        </daySchedule>
    </timeslot>
    <timeslot start="12:30" finish="14:30">
        <daySchedule day ="Wednesday"> 
            <course>
                <courseID id="4850"></courseID>
                <className></className>
                <classLocation></classLocation>
                <classActivity activity="lecture"></classActivity>
            </course>
        </daySchedule>
    </timeslot>
    <timeslot start="10:30" finish="12:30">
        <daySchedule day ="Thursday">
            <course>
                <courseID id="4850"></courseID>
                <className></className>
                <classLocation></classLocation>
                <classActivity activity="lab"></classActivity>
            </course>
        </daySchedule>
    </timeslot>
</timeslots>

=== 4850-XML/4850Lab7/data/days_facet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE days SYSTEM "classSchedule.dtd">
<!--
    Document   : days_facet.xml
    Created on : March 06, 2016
    Author     : Khang
    Description:
        The days of of the week of our winter 2016 class schedule. This xml 
        document displays the days of the week from Monday-Friday
-->
    <days> 
        <daySchedule day ="Monday"> 
            <timeslot start="13:30" finish="15:30">
                <course>
                    <courseID id="4770"></courseID>
                    <className></className>
                    <classLocation></classLocation>
                    <classActivity></classActivity>
                </course>
            </timeslot>
            <timeslot start="13:30" finish="15:30">
                <course>
                    <courseID id="4770"></courseID>
                    <className></className>
                    <classLocation></classLocation>
                    <classActivity></classActivity>
                </course>
            </timeslot>
        </daySchedule>
        <daySchedule day ="Tuesday"> 
            <timeslot start="10:30" finish="12:30">
                <course>
                    <courseID id="4620"></courseID>
                    <className></className>
                    <classLocation></classLocation>
                    <classActivity activity="lab"></classActivity>
                </course>
            </timeslot>
            <timeslot start="15:30" finish="17:30">
                <course>
                    <courseID id="4620"></courseID>
                    <className></className>
                    <classLocation></classLocation>
                    <classActivity activity="lecture"></classActivity>
                </course>
            </timeslot>
        </daySchedule> 
        <daySchedule day ="Wednesday"> 
            <timeslot start="12:30" finish="14:30">
                <course>
                    <courseID id="4850"></courseID>
                    <className></className>
                    <classLocation></classLocation>
                    <classActivity activity = "lecture"></classActivity>
                </course>
            </timeslot>
        </daySchedule>  
        <daySchedule day ="Thursday"> 
            <timeslot start="10:30" finish="12:30">
                <course>
                    <courseID id="4850"></courseID>
                    <className></className>
                    <classLocation></classLocation>
                    <classActivity activity="lab"></classActivity>
                </course>
            </timeslot>
        </daySchedule> 
        <daySchedule day ="Friday"> 
        </daySchedule> 
    </days>
